CREATE TABLE IF NOT EXISTS USERS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vk_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    fam VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PREFERS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vk_id INT REFERENCES USERS(id),
    pref VARCHAR(2047) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRESENTS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    from_id INT REFERENCES USERS(id),
    to_id INT REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS GIVERS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vk_id INT REFERENCES USERS(id)
)